services:
  - type: web
    name: deepfake-backend
    env: python
    buildCommand: python -m pip install --upgrade pip && python -m pip install --index-url https://download.pytorch.org/whl/cpu torch torchvision && python -m pip install -r requirements.txt
    startCommand: python -m uvicorn app:app --host 0.0.0.0 --port $PORT
